name: torch-cpu image
# manually trigger the workflow
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag torch:2.2.2-cpu
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image to Docker Hub
      run: docker tag torch:2.2.2-cpu xiaoql/torch:2.2.2-cpu
    - run: docker push xiaoql/torch:2.2.2-cpu
